dataset:
  name: threedganshapenet
  filelist_train:
    - 03001627_train.lst
  filelist_test:
    - 03001627_test.lst
model:
  backbone: null
  name: threedgan
num_gpus: 1
checkpoint: "experiments/checkpoints/gan3d/3dgan_train_0305221653/223410_000677.pt"
num_workers: 4
name: gan3d
test:
  batch_size: 1
  shuffle: false
train:
  batch_size: 8
  num_epochs: 1000
  backbone_pretrained_model: null
optim:
  name: "adam_gan"
  adam_beta1: 0.5
  adam_beta2: 0.5
  lr_d: 0.0025
  lr_g: 0.001
  lr_scheduler: "multistep_gan"
  lr_step:
    - 500
    - 1000